print ("Hallo, ich bin ein Computer.")
name = input("Wie ist dein Name? ")
print ("Schön dich zu treffen ", name, ".", sep="")
print ("Dein Name ist ", len(name), "Zeichen lang.")
alter = input("Wie alt bist du? ")
print ("Nächstes Jahr wirst du", int(alter)+1, "Jahre alt sein.")
